[build]
rootDirectory = "."

[deploy]
startCommand = "cd backend && python manage.py migrate --noinput && gunicorn app.wsgi:application --bind 0.0.0.0:8000"
healthcheckPath = "/"

[deploy.preDeploy]
command = "python manage.py migrate --noinput"
